#!/usr/bin/env python3

import argparse

# TODO solve for h (I think lol) @zoe/@alessandra
def solve(mdot, Cp, Tin, Tout, Twall, Tmid, area):
    # NOTE there might be more inputs than these... if there are,
    # please make changes where necessary... good luck (●'◡'●)
    h = 0
    return h

# TODO design an input file and make this parse it @conor
def readInputfile(filename):
    mdot  = 0
    Cp    = 0
    Tin   = 0
    Tout  = 0
    Twall = 0
    Tmid  = 0
    area  = 0
    return mdot, Cp, Tin, Tout, Twall, Tmid, area

if __name__ == '__main__':
    # ARG PARSING ==========================
    parser = argparse.ArgumentParser(description='Team Cooliest\'s ~ proprietary ~ model.')
    subparser = parser.add_subparsers(dest='subparser')
    # Input File ---------------------------
    inputfile = subparser.add_parser('inputfile')
    inputfile.add_argument('-f', '--filename',
                           type=str,
                           required=True,
                           help='Name of the input file.')
    # Arguments ----------------------------
    # TODO add units in all of the help strings
    args = subparser.add_parser('args')
    args.add_argument('--mdot',
                      type=float,
                      required=True,
                      help='Mass flow rate (put units here).')
    args.add_argument('--Cp',
                      type=float,
                      required=True,
                      help='Pressure coefficient (put units here).')
    args.add_argument('--Tin',
                      type=float,
                      required=True,
                      help='Inlet temperature (put units here).')
    args.add_argument('--Tout',
                      type=float,
                      required=True,
                      help='Outlet temperature (put units here).')
    args.add_argument('--Twall',
                      type=float,
                      required=True,
                      help='Wall temperature (put units here).')
    args.add_argument('--Tmid',
                      type=float,
                      required=True,
                      help='Middle temperature (put units here).')
    args.add_argument('-A', '--area',
                      type=float,
                      required=True,
                      help='Cross-sectional area (put units here).')
    # SOLVE ================================
    pargs = parser.parse_args()
    if (pargs.subparser == 'inputfile'):
        mdot, Cp, Tin, Tout, Twall, Tmid, area = readInputfile(pargs.filename)
    elif (pargs.subparser == 'args'):
        mdot  = pargs.mdot
        Cp    = pargs.Cp
        Tin   = pargs.Tin
        Tout  = pargs.Tout
        Twall = pargs.Twall
        Tmid  = pargs.Tmid
        area  = pargs.area
    h = solve(mdot, Cp, Tin, Tout, Twall, Tmid, area)
    # POST PROCESSING ======================
    print(h)
