#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
rm -r 0.*
rm -r 1.*
rm log.*
rm job.*

#------------------------------------------------------------------------------
